version: '1.0'

services:
  db:
    env_file: ".env"
    image: mysql:8.0
    container_name: ecommerce_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: ecommerce_backend
    env_file: ".env"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/${MYSQL_DATABASE}"
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - db

  frontend:
    build:
      context: ./src/main/frontend
    container_name: ecommerce_frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  db_data: